---
# Main tasks for OWASP ZAP installation and ZaaS (ZAP as a Service) configuration

- name: Create ZAP user and group
  user:
    name: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    shell: /bin/bash
    create_home: yes
    home: "{{ zaproxy_home | default('/opt/zaproxy') }}"
    state: present
  become: yes

- name: Install required dependencies
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-pip
      - unzip
    state: present
  become: yes

- name: Install Docker dependencies
  pip:
    name:
      - docker
      - docker-compose
      - requests
      - flask
    state: present
  become: yes

- name: Create ZAP directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    mode: 0755
  loop:
    - "{{ zaproxy_home | default('/opt/zaproxy') }}"
    - "{{ zaproxy_home | default('/opt/zaproxy') }}/data"
    - "/opt/zaas"
    - "/opt/zaas/static"
    - "/opt/zaas/static/reports"
    - "/opt/zaas/templates"
  become: yes

- name: Copy ZAP Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ zaproxy_home | default('/opt/zaproxy') }}/Dockerfile"
    owner: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    mode: 0644
  become: yes

- name: Copy ZAP docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ zaproxy_home | default('/opt/zaproxy') }}/docker-compose.yml"
    owner: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    mode: 0644
  become: yes

- name: Copy ZAP API daemon script
  template:
    src: zap-api-daemon.sh.j2
    dest: "{{ zaproxy_home | default('/opt/zaproxy') }}/zap-api-daemon.sh"
    owner: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    mode: 0755
  become: yes

- name: Copy ZAP configuration properties
  template:
    src: config.properties.j2
    dest: "{{ zaproxy_home | default('/opt/zaproxy') }}/config.properties"
    owner: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    mode: 0644
  become: yes

# ZaaS (ZAP as a Service) specific tasks
- name: Copy ZaaS web interface script
  template:
    src: zapweb.py.j2
    dest: "/opt/zaas/zapweb.py"
    owner: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    mode: 0755
  become: yes

- name: Copy ZaaS CLI script
  template:
    src: zapcli.py.j2
    dest: "/opt/zaas/zapcli.py"
    owner: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    mode: 0755
  become: yes
  
- name: Create symlink to ZaaS CLI script in /usr/local/bin
  file:
    src: "/opt/zaas/zapcli.py"
    dest: "/usr/local/bin/zapcli"
    state: link
    mode: 0755
  become: yes

- name: Copy ZaaS web template
  template:
    src: static/templates/index.html.j2
    dest: "/opt/zaas/templates/index.html"
    owner: "{{ zaproxy_user | default('zaproxy') }}"
    group: "{{ zaproxy_group | default('zaproxy') }}"
    mode: 0644
  become: yes

- name: Create ZaaS systemd service file
  template:
    src: zaproxy.service.j2
    dest: "/etc/systemd/system/zaproxy.service"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart ZaaS service

- name: Start docker-compose ZAP container
  shell: "cd {{ zaproxy_home | default('/opt/zaproxy') }} && docker-compose up -d"
  become: yes
  become_user: "{{ zaproxy_user | default('zaproxy') }}"
  
- name: Enable and start ZaaS service
  systemd:
    name: zaproxy
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
